set(EXTERNAL_DEPENDENCIES_DIR_NAME "MixedAnalysisExternalDependencies")
set(EXTERNAL_DEPENDENCIES_PATH "$ENV{HOME}/${EXTERNAL_DEPENDENCIES_DIR_NAME}")
set(EXTERNAL_DEPENDENCIES_BINARIES_PATH "${EXTERNAL_DEPENDENCIES_PATH}/Install")

file(MAKE_DIRECTORY ${EXTERNAL_DEPENDENCIES_PATH})
file(MAKE_DIRECTORY ${EXTERNAL_DEPENDENCIES_BINARIES_PATH})

set(CWE_CHECKER_COMPONENT_NAME "CweChecker")
add_subdirectory("${EXTERNAL_DEPENDENCIES_SRC_DIR}/${CWE_CHECKER_COMPONENT_NAME}")

set(CPP_CHECK_COMPONENT_NAME "CppCheck")
add_subdirectory("${EXTERNAL_DEPENDENCIES_SRC_DIR}/${CPP_CHECK_COMPONENT_NAME}")

set(QT_COMPONENT_NAME "Qt5")
# NOTE: Use include instead of add_subdirectory to make Qt packages visible in the parent score.
include(${EXTERNAL_DEPENDENCIES_SRC_DIR}/${QT_COMPONENT_NAME}/CMakeLists.txt)